services:
  - type: web
    name: jobanalyzerdashboard-api
    env: dotnet
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    domains:
      - jobanalyzerdashboard.onrender.com
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000
      - key: ConnectionStrings__DefaultConnection
        value: "postgresql://n8n_db_7rcs_user:tTT6Uaxnv5FrGFKbqiLz1LAGgwSGQRIv@dpg-d034egali9vc73edf1og-a.oregon-postgres.render.com/n8n_db_7rcs"
      - key: JwtSettings__Secret
        value: "YourSuperSecretKeyThatIsAtLeast32CharactersLongForSecurityReasons123456789"
      - key: JwtSettings__Issuer
        value: JobAnalyzerDashboard
      - key: JwtSettings__Audience
        value: JobAnalyzerDashboardUsers
      - key: JwtSettings__ExpirationInMinutes
        value: 60
      - key: Authentication__Google__ClientId
        sync: false
      - key: Authentication__Google__ClientSecret
        sync: false
      - key: Authentication__Google__RedirectUri
        sync: false
      - key: AppSettings__BaseUrl
        sync: false

# Mevcut n8n veritabanını kullanıyoruz, bu yüzden yeni veritabanı oluşturmuyoruz
# databases:
#   - name: jobanalyzerdashboard-db
#     plan: free
#     databaseName: jobanalyzerdashboard
#     user: jobanalyzerdashboard_user
