services:
  - type: web
    name: jobanalyzerdashboard-api
    env: dotnet
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    domains:
      - jobanalyzerdashboard.onrender.com
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000
      - key: ConnectionStrings__DefaultConnection
        value: "postgresql://n8n_db_7rcs_user:tTT6Uaxnv5FrGFKbqiLz1LAGgwSGQRIv@dpg-d034egali9vc73edf1og-a.oregon-postgres.render.com/n8n_db_7rcs"
      - key: JwtSettings__Secret
        value: "YourSuperSecretKeyThatIsAtLeast32CharactersLongForSecurityReasons123456789"
      - key: JwtSettings__Issuer
        value: JobAnalyzerDashboard
      - key: JwtSettings__Audience
        value: JobAnalyzerDashboardUsers
      - key: JwtSettings__ExpirationInMinutes
        value: 60
      - key: Authentication__Google__ClientId
        value: "602631296713-kueq8lm3tsc3ms8ff87de29f4r7bjjjd.apps.googleusercontent.com"
      - key: Authentication__Google__ClientSecret
        value: "GOCSPX-717SkyWhuTcanQmmpmlj1BCtK44"
      - key: Authentication__Google__RedirectUri
        value: "https://jobanalyzerdashboard.onrender.com/api/auth/google/callback"
      - key: Authentication__Google__Scopes
        value: "https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
      - key: AppSettings__BaseUrl
        value: "https://jobanalyzerdashboard.onrender.com"
      - key: AppSettings__FrontendUrl
        value: "https://jobanalyzerdashboard.onrender.com"

# Mevcut n8n veritabanını kullanıyoruz, bu yüzden yeni veritabanı oluşturmuyoruz
# databases:
#   - name: jobanalyzerdashboard-db
#     plan: free
#     databaseName: jobanalyzerdashboard
#     user: jobanalyzerdashboard_user
